pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    sh './build.sh'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'pytest tests/'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh './deploy.sh'
                }
            }
        }
    }
}
